"""Change in Auth Table

Revision ID: 6ddc44899203
Revises: a336ee5ddd33
Create Date: 2020-02-02 09:28:39.432354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ddc44899203'
down_revision = 'a336ee5ddd33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_auth_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=100), nullable=True),
    sa.Column('generate_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_auth_key_expiry_date'), 'api_auth_key', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_api_auth_key_generate_date'), 'api_auth_key', ['generate_date'], unique=False)
    op.drop_index('ix_api_auth_table_expiry_date', table_name='api_auth_table')
    op.drop_index('ix_api_auth_table_generate_date', table_name='api_auth_table')
    op.drop_table('api_auth_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_auth_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('API_key', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('generate_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expiry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='api_auth_table_pkey')
    )
    op.create_index('ix_api_auth_table_generate_date', 'api_auth_table', ['generate_date'], unique=False)
    op.create_index('ix_api_auth_table_expiry_date', 'api_auth_table', ['expiry_date'], unique=False)
    op.drop_index(op.f('ix_api_auth_key_generate_date'), table_name='api_auth_key')
    op.drop_index(op.f('ix_api_auth_key_expiry_date'), table_name='api_auth_key')
    op.drop_table('api_auth_key')
    # ### end Alembic commands ###
