"""Added Audio Info in VideoPosts table

Revision ID: 92d5bbf2375a
Revises: 33d7ff1455e0
Create Date: 2020-01-31 18:57:42.287450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d5bbf2375a'
down_revision = '33d7ff1455e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_post', sa.Column('audio_info', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_post', 'audio_info')
    # ### end Alembic commands ###
