"""Added APIAuthentincation Table,Added isActive ,LastLogin Column in User Table,Added Audio info column in Videopost

Revision ID: a336ee5ddd33
Revises: 92d5bbf2375a
Create Date: 2020-02-01 08:00:24.117876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a336ee5ddd33'
down_revision = '92d5bbf2375a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_auth_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('API_key', sa.String(length=100), nullable=True),
    sa.Column('generate_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_auth_table_expiry_date'), 'api_auth_table', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_api_auth_table_generate_date'), 'api_auth_table', ['generate_date'], unique=False)
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('lastonline_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_lastonline_time'), 'user', ['lastonline_time'], unique=False)
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_index('ix_user_first_name', table_name='user')
    op.drop_index('ix_user_last_name', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_last_name', 'user', ['last_name'], unique=False)
    op.create_index('ix_user_first_name', 'user', ['first_name'], unique=False)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_index(op.f('ix_user_lastonline_time'), table_name='user')
    op.drop_column('user', 'lastonline_time')
    op.drop_column('user', 'is_active')
    op.drop_index(op.f('ix_api_auth_table_generate_date'), table_name='api_auth_table')
    op.drop_index(op.f('ix_api_auth_table_expiry_date'), table_name='api_auth_table')
    op.drop_table('api_auth_table')
    # ### end Alembic commands ###
